# Generated by Django 3.0.2 on 2020-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('in_date', models.DateTimeField(auto_now=True, null=True)),
                ('out_date', models.DateTimeField(default=None, null=True)),
                ('presente', models.BooleanField(default=True)),
            ],
        ),
    ]
